### ISSUE TITLE
Running 5_opendkim.sh in batch mode

### ISSUE THREAD

**Issue by jvaubourg** [polytan02/yunohost_auto_config_basic#4]
Hi,

I would like to run `5_opendkim.sh` in batch mode, without human interaction.

Currently, it's not possible because this script asks for a domain to use and a confirmation before installing. Only language can be set with an argument.

Could you add options to the script, enabling to run it without interaction?

**Comment by polytan02** [comment]
Hi Julien, 

Yes, it can be modified easily. I will look at this as soon a possible.

**Comment by polytan02** [comment]
So,

The latest commit https://github.com/polytan02/yunohost_auto_config_basic/commit/664ec99e1cb743d9007114709865cbd1a7a3dbc4 shows a new script called 5_opendkim_auto.sh

You should be able to use this script like this : 

./5_opendkim_auto.sh fr domain.tld

or

./5_opendkim_auto.sh en myotherdomain.com
(for the english version)

Is this suitable for what you want to do ? :)

**Comment by jvaubourg** [comment]
It's perfect for me :). Thank you very much (very late).
